appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Nno1GLcd+/PQyEGrM3QTWLjKk224YkbJKOHiIAHlK3U2dJjXWp81GYup07cxC6A24ROGmKBlzRJNOn9rO98MKK6wXhi58Jn8xYSkRVQhSBYhxlC2k/ThsTn7NnkjMtm/L5CnVugm39y7aBrFyXvqscWisfG7BTwrqZud9APzEH/ZLO/kMXN+qxths8wvPiCRxV7bybICA4B4k/cBC9OKsO7FJRFIdUupEOaZEycv1neoYqbBl/pih0w4Fmig0AVongD1+I942js4pmwvMFmy2vIrR1fUpim9cWLvQ1PZXfGD9R7aLrFNfRWQst2/sEXwem1LJddawZiyfHybAOhZbPeZMV4N1gA13rPoM8OrnGgRJBxHoey3c8WVH+tuUjHgH8xvwvq4xmPzaFjMXQ+Frr9ui35Nv7njY6HI8MFzwRaCAGwLBtbCrhRiwqnogvgzgNgIIZLmTKWCeah7/nXyFIIqkKl5e7ZXvWGwc7nW/grWXNzenso8C8+9Sy6zTAopEoGURki4XeEQumysB8l3ScweMKaColPN/Bv0bLC6P9UUcIsQV6pa4zVLVLIAqcrDI1U8lBPuM8K4eWjuFREXda7Xy5jtMie/gew062wmCoScxZDpfIgJ7SuHnDq5nTxReTnI0mBEw6C6IxrZvIHgWhuy0TIFBrSkLClqPyngq+0=}
